# site
url: https://ultradao.org
author: Chris Wallace
title: "UltraDAO" # the name of your site, e.g. ACME Corp.

# markdown
markdown: kramdown
highlighter: rouge

# paginator
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 2
paginate_path: "/page:num"

# google analytics
google_analytics_id: "G-83XY96FNML"

# other configs
exclude: ["CNAME", "README.md"]
